### ISSUE TITLE
[BACKEND] Errore nella disabilitazione TFA

### ISSUE THREAD

**Issue by aletomm** [RedRoundRobin/swe-webapp#101]
**Descrizione del bug**
Una volta che viene disattivata l'opzione di TFA dopo che è stata correttamente attivata e salvata, provoca un errore nella pagina.
Ovvero se: Inserisco username Telegram -> salvo -> faccio login sul bot -> abilito TFA nella webapp -> salvo -> disabilito l'opzione TFA su webapp -> errore.

**Modifica da fare**

**Comment by Maxelweb** [comment]
Nuovo bug per @nfrison: se disabilito il TFA, non devo cancellare la chat id se sono un utente normale.

**Comment by nfrison** [comment]
Risolto qui redroundrobin/swe-api#143
