### ISSUE TITLE
[BACKEND] Manca la possibilità di riassegnare un membro ad un altro ente

### ISSUE THREAD

**Issue by nfrison** [RedRoundRobin/swe-webapp#103]
**Descrizione del bug**
RA-F-25: Un amministratore deve poter riassegnare un membro o un
moderatore ente a ente differente

**Modifica da fare**
Deve essere possibile riassegnare un utente ad un altro ente

**Tipo di browser**
DESKTOP / MOBILE

> **ATTENZIONE:** le api devono rimuovere anche gli alert che sono stati disabilitati da un utente in quel caso, nonché le view con i sensori abilitati, ecc.

**Comment by Maxelweb** [comment]
> **ATTENZIONE:** le api devono rimuovere anche gli alert che sono stati disabilitati da un utente in quel caso, nonché le view con i sensori abilitati, ecc.

**Comment by nfrison** [comment]
Fixato lato api RedRoundRobin/swe-api#141

**Comment by Maxelweb** [comment]
@nfrison Non ancora funzionante. Errore 500 quando si tenta di eseguire l'update.
