### ISSUE TITLE
[BACKEND] Al cambio email da un'altra parte non posso più fare niente

### ISSUE THREAD

**Issue by nfrison** [RedRoundRobin/swe-webapp#104]
**Descrizione del bug**
Ho modificato la email dall'amministratore di un utente con cui ero connesso su firefox (con l'admin su chrome). Dopo aver modificato la email ho provato a navigare con l'utente su firefox e mi ha ritornato l'errore 403 forbidden. Da lì non ho più potuto muovermi, non ci sono indicazioni per il relogin e anche andando alla pagina di login non succede niente. Provando anche a pulire la cache ma nada.

**Modifica da fare**
Non deve bloccarsi tutto se mi cambiano la email

**Comment by Maxelweb** [comment]
Ho discusso con @nfrison 
Il problema si dovrebbe ripresentare anche quando viene cambiata la password, sempre da un admin, quando un utente è loggato.
Le soluzioni sono due:
- O si gestisce impropriamente che un errore 403 è dovuto sempre a un cambio di impostazioni di un utente, e dunque si fa force dell'utente a eseguire logout e rientrare (soluzione peggiore).

> da `BasicProvider.php` fare un ` || $e->getCode() == 403`

- Oppure si cambia il JWT in modo più indolore lato API, integrando solamente lo USER_ID al posto dell'email e della password che sono impostazioni che possono cambiare. Il controllo verrà eseguito sempre sullo USER_ID

**Comment by Maxelweb** [comment]
L'alternativa è fare entrambe le cose.
