### ISSUE TITLE
[BACKEND] Visualizzazione ente di appartenenza di utente da parte di moderatore

### ISSUE THREAD

**Issue by nfrison** [RedRoundRobin/swe-webapp#107]
**Descrizione del bug**
Visualizzando da moderatore le informazioni di un utente viene visualizzato come ente "-"

**Modifica da fare**
Credo debba vedersi il nome dell'ente anche se intuitivo

**Comment by BroHPotato** [comment]
problema API, /entities?userId={id} ma richiede ?user={Id} @nfrison

**Comment by nfrison** [comment]
Lato api è richiesto userId, non user

**Comment by BroHPotato** [comment]
allora una richiesta da parte del mod mi ritorna vuota

**Comment by nfrison** [comment]
PullRequest RedRoundRobin/swe-api#150
