### ISSUE TITLE
[BACKEND] Lista utenti ente errata

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#108]
**Descrizione del bug**
Se entro dentro Gestisci ente, mi vedo la lista degli utenti appartenenti all'ente che è sbagliata. Ci sono anche gli amministratori.

**Modifica da fare**
Ci devono essere solo i membri appartenenti all'ente

**Comment by BroHPotato** [comment]
gia risolta, sono cambiate le querystring e su develop non e' presente il cambiamento
