### ISSUE TITLE
[BACKEND] Errore nell'aggiunta di un device con gateway e realDeviceId già presenti

### ISSUE THREAD

**Issue by nfrison** [RedRoundRobin/swe-webapp#110]
**Descrizione del bug**
Ho provato ad aggiungere un dispositivo con un sensore associato, che esiste già e non mi viene visualizzata una pagina di errore appropriata, ma questa:
![image](https://user-images.githubusercontent.com/56256087/81672178-12ac6480-944a-11ea-95f2-8703ccb3407b.png)

**Modifica da fare**
Sistemare

**Comment by BroHPotato** [comment]
heh ritorna un errore 400, ma siccome e' un conflitto dovrebbe ritornare 409 come errore

**Comment by nfrison** [comment]
Giusto, sistemo
