### ISSUE TITLE
[BACKEND] Se entro nella modifica del gateway e non altero il nome, ritorna errore 400

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#118]
**Descrizione del bug**
Se entro nella modifica del gateway e non altero il nome del gateway, ritorna errore 400

**Modifica da fare**
Deve darmi successo, come in tutti gli altri casi.

**Comment by BroHPotato** [comment]
fixato, ma bisogna sistemare anche dalle API

**Comment by BroHPotato** [comment]
se mando una richiesta di update con gli stessi dati non mi dovrebbe rispondere con 400 ma dovrebbe inviarla lo stesso, nel senso posso sovrascrivere i dati con gli stessi gia presenti

**Comment by FouadM96** [comment]
Ok per il secondo commento, ma per il primo non capisco. Cioè, name è l'unico campo dati del gateway che si può editare e se si fa una richiesta di edit senza un json al suo interno col campo name secondo me ha senso avvisare con un errore che la richiesta non è ben formata... O no?
