### ISSUE TITLE
[Test] Controlli da fare 

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#120]
# @aletomm 

### Amministratore

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Alerts (creazione, eliminazione, modifica)
- [ ] Gestione Utenti (creazione, disattivazione, modifica)
- [x] Gestione enti (creazione, disattivazione, modifica, aggiunta / rimozione sensori a ente)
- [x] Gestione Dispositivi (creazione, disattivazione, modifica)
- [x] Gestione Gateway (creazione, disattivazione, modifica)
- [x] Logout

### Utente

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Logout

### Moderatore

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Alerts (creazione, eliminazione, modifica)
- [x] Gestione Utenti (creazione, disattivazione, modifica)
- [x] Logout

# @nfrison 

### Moderatore

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Alerts (creazione, eliminazione, modifica)
- [x] Gestione Utenti (creazione, disattivazione, modifica)
- [x] Logout

### Amministratore

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Alerts (creazione, eliminazione, modifica)
- [x] Gestione Utenti (creazione, disattivazione, modifica)
- [x] Gestione enti (creazione, disattivazione, modifica, aggiunta / rimozione sensori a ente)
- [x] Gestione Dispositivi (creazione, disattivazione, modifica)
- [x] Gestione Gateway (creazione, disattivazione, modifica)
- [x] Logout

### Utente

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Logout

# @Maxelweb 

### Utente

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Logout

### Moderatore

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Alerts (creazione, eliminazione, modifica)
- [x] Gestione Utenti (creazione, disattivazione, modifica)
- [x] Logout

### Amministratore

- [x] Impostazioni (tutte)
- [x] Alerts (tutti)
- [x] Dispositivi e sensori (tutto)
- [x] Grafico sensore singolo
- [x] Pagina view (creazione, cancellazione di un grafico, cancellazione singola, ecc.)
- [x] Alerts (creazione, eliminazione, modifica)
- [x] Gestione Utenti (creazione, disattivazione, modifica)
- [x] Gestione enti (creazione, disattivazione, modifica, aggiunta / rimozione sensori a ente)
- [x] Gestione Dispositivi (creazione, disattivazione, modifica)
- [x] Gestione Gateway (creazione, disattivazione, modifica)
- [x] Logout

**Comment by aletomm** [comment]
ADMIN errore 500 alla creazione di un utente

**Comment by Maxelweb** [comment]
MOD errore {ROUTE} Missing required parameters for [Route: devices.show] [URI: devices/{deviceId}]. (View: /usr/src/webapp/resources/views/alerts/index.blade.php) quando si entra su Alerts o Impostazioni

--> Se un sensore viene eliminato quando è aggiunto a un ente, rimangono comunque gli alert relativi a quel sensore.
