### ISSUE TITLE
[FRONTEND] Sistemare i titoli nelle sezioni

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#13]
**Descrizione del bug**
Mancano i titoli di sezione (quelli fuori dai card) quando faccio aggiungi / modifica

**Modifica da fare**
Vanno aggiunti e allineati i titoli delle macro sezioni, in modo simile alla dashboard.

**Tipo di browser**
DESKTOP / MOBILE

**Comment by aletomm** [comment]
- [x] Dispositivi/sensori
- [ ] Gateway
- [ ] Utenti
