### ISSUE TITLE
[BACKEND] Unione della pagina dettaglio di un dispositivo con la lista sensori

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#14]
**Descrizione del bug**
Avere una pagina unica, consente di visualizzare più informazioni in un colpo e così riduciamo i bottoni a uno. La pagina dettaglio dispositivo e lista sensori sono attualmente separate.

**Modifica da fare**
La root `/devices/1/` mostra i dettagli + la lista dei sensori
Quando apro un sensore, la root si trasformerà comunque in `/devices/1/sensors/id_sensore`

**Comment by aletomm** [comment]
@Maxelweb @BroHPotato 
Non avevo visto la issue ed ho unito la lista dei sensori nella pagina dei dettagli del dispositivo (show). Non ho comunque eliminato la pagina index dei sensors anche se al momento non è più accessibile. Tutto queso nel branch feature/gestioneDispositivi
