### ISSUE TITLE
[BACKEND] I grafici non devono partire da un grafico vuoto, ma devono usare i dati vecchi (ultimi ~20 dati)

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#47]
**Descrizione del bug**
Il grafico mostra solo dei dati randomici

**Modifica da fare**
Il grafico dovrebbe mostrare gli ultimi N dati (~20) mentre vengono aggiornati i nuovi dati. Possono rimanere come essere buttati.

**Comment by BroHPotato** [comment]
@nfrison c'e` una chiamata /data/{sensorId}&limit=20 ??

**Comment by nfrison** [comment]
Mi sa di no. C'è/data?sensors=id&limit=n

**Comment by Maxelweb** [comment]
Nicolò mi disse ieri sera che già riporta il limite a 20 registrazioni, giusto? @nfrison

**Comment by nfrison** [comment]
No ma puoi settarlo nella query di /data con key limit

**Comment by BroHPotato** [comment]
btw non ce la faccio a risolverla prima dell'RQ

**Comment by Maxelweb** [comment]
Ok. @BroHPotato Riesci a usare un mock di dati preesistenti appena si genera il grafico? Ossia far partire il grafico con 20 dati inventati e poi aggiornare con nuovi dati randomici man mano?
