### ISSUE TITLE
[BACKEND] Aggiungere possibilità di creare un grafico con un solo sensore nelle view

### ISSUE THREAD

**Issue by nfrison** [RedRoundRobin/swe-webapp#48]
**Descrizione del bug**
La visualizzazione di un grafico nelle view necessità di due sensori

**Modifica da fare**
La visualizzazione di un grafico nelle view deve avere bisogno di almeno un sensore, non necessariamente entrambi

**Comment by BroHPotato** [comment]
la creazione di una view richiede l'input di entrambi i sensori, non ha senso creare una view con un solo sensore anche perche non si potrebbe calcolare le varie varianze

**Comment by BroHPotato** [comment]
per visualizzare un solo sensore c'e` la pagina del sensore singolo

**Comment by nfrison** [comment]
Per me una persona che usa l'applicativo dovrebbe avere la possibilità di vedere in un grafico un solo sensore senza correlazioni. A mio parere, se non è troppo impegnativo lato webapp, ci starebbe l'implementazione. Lato API già quando l'ho fatto pensavo ci potesse stare anche solo un sensore, quindi lì è già implementato
