### ISSUE TITLE
[FRONTEND/BACKEND] Aggiungere la possibilità di visualizzare gli enti per un dato sensore e di aggiungerli / rimuoverli

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#58]
**Modifica da fare**
Dalla pagina entity.show deve essere possibile fare le seguenti cose:

- Visionare le info di un ente
- vedere una lista con gli utenti per l'ente
- vedere una lista con i sensori abilitati per l'ente
- aggiungere un sensore con un dropdown menù (come quello delle view)
- rimuovere un sensore a un ente con un bottone dalla lista dei sensori abilitati

![idea view](https://i.imgur.com/H3v76WC.png)

**Comment by BroHPotato** [comment]
comunicate quando sono pronte le pagine che le collego con il backend

**Comment by aletomm** [comment]
@Maxelweb Ma l'aggiunta di un sensore non ha senso farla nella pagina di edit?

**Comment by Maxelweb** [comment]
No, dalla pagina di un sensore ha senso vedere gli enti autorizzati per quel sensore @aletomm

**Comment by aletomm** [comment]
@Maxelweb Ma oltre al fatto di aggiungere / rimuovere/ visualizzare i sensori per un certo ente dalla pagina show dell'ente, vuoi che dalla pagina show dei sensori si visualizzino gli enti e basta, senza poter fare modifiche, giusto?

**Comment by Maxelweb** [comment]
@aletomm Se fosse ez da fare sì. Così si puo vedere sia da ente verso sensori, che da un sensore verso enti, ma solo per gli admin.

**Comment by aletomm** [comment]
Io ho fatto entrambe le cose
Poi lascerei a @BroHPotato la scelta di tenere la lista degli enti anche nella pagina dei sensori in base alla difficoltà

**Comment by BroHPotato** [comment]
la pagina dei sensori e' easy, gia' fatta, ora mi metto sotto per le entities

**Comment by BroHPotato** [comment]
la tabella in entities.show si rompe quando ci sono i dati

**Comment by aletomm** [comment]
Quella con i sensori?

**Comment by BroHPotato** [comment]
yup

**Comment by aletomm** [comment]
Perchè sfora sulla destra ed esce dalla card?
Adesso ho un attimo da fare, appena ho 5 min mi metto

**Comment by aletomm** [comment]
@BroHPotato Il campo `device` di un sensore cosa contiene di preciso?

**Comment by BroHPotato** [comment]
allora, ora pusho le modifiche, pero' bisogna fare la stessa cosa del js e dei form per che abbiamo fatto sulla gestione device

**Comment by BroHPotato** [comment]
contiene l'id del device a cui appartiene un sensore

**Comment by aletomm** [comment]
ok, allora spetto le tue modifiche e poi modifico

**Comment by BroHPotato** [comment]
fatto
