### ISSUE TITLE
[BACKEND] I grafici devono mostrare un po' di dati precedenti

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#70]
**Descrizione del bug**
I grafici caricano lentamente solo a partire dall'inizio della loro apertura e non mostrano un minimo di storico di 20 dati precedenti

**Modifica da fare**
Vanno caricati i primi 20 dati precedenti, se possibile e poi aggiunti in append quelli nuovi

**Comment by BroHPotato** [comment]
La issue non riguarda la webapp
