### ISSUE TITLE
[BACKEND] Indirizzo IP errato

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#78]
**Descrizione del bug**

Nelle logs, l'indirizzo IP riportato è errato.

**Modifica da fare**

- Se si va in dashboard l'indirizzo IP riportato è corretto. Quelle nelle logs, invece, no.

**Comment by BroHPotato** [comment]
l'indirizzo ip lo invio con la richiesta, ed e' lo stesso che mostro in dashboard (aka request()->ip()) quindi e' dalla parte api che non gli inseriscono bene

**Comment by Maxelweb** [comment]
> l'indirizzo ip lo invio con la richiesta, ed e' lo stesso che mostro in dashboard (aka request()->ip()) quindi e' dalla parte api che non gli inseriscono bene

@nfrison @FouadM96 c'è qualche problema nella registrazione dell'ip
