### ISSUE TITLE
[FRONTEND] Fixare bottone btn-small su aggiunta / edit dispositivi

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-webapp#98]
**Descrizione del bug**
Il bottone non è allineato correttamente ed è troppo grande

**Modifica da fare**
Fixare bottone btn-small su aggiunta / edit dispositivi in `btn-sm`

**Tipo di browser**
DESKTOP / MOBILE

**Comment by aletomm** [comment]
@Maxelweb Quali bottons devono essere small?
